export const SET_INIT_SEQUENCER = 'SET_INIT_SEQUENCER'

export const UPDATE_SEQUENCE = 'UPDATE_SEQUENCE'

export const CHANGE_PATTERN = 'CHANGE_PATTERN'

export const SAVE_PATTERN = 'SAVE_PATTERN'

export const LOAD_PATTERN = 'LOAD_PATTERN'

export const CHANGE_PATTERN_NAME = 'CHANGE_PATTERN_NAME'

export const SET_INDEX = 'SET_INDEX'

export const UPDATE_SEQUENCER_STATUS = 'UPDATE_SEQUENCER_STATUS'